### 数组的创建和访问

In [42]:
import numpy as np

In [4]:
# create from python list
list_1 = [1,2,3,4]
array_1 = np.array(list_1)
print(type(array_1),array_1)

<class 'numpy.ndarray'> [1 2 3 4]


In [5]:
list_2 = [5,6,7,8]
array_2 = np.array([list_1,list_2])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
array_2.shape

(2, 4)

In [7]:
array_2.size  # 

8

In [8]:
array_2.dtype

dtype('int32')

In [17]:
array_3 = np.array([[1.0,2,3],[4,5,6]])  # 其中只要有一个是float，那么所有都是float
print(type(array_3),array_3)
array_3.dtype

<class 'numpy.ndarray'> [[1. 2. 3.]
 [4. 5. 6.]]


dtype('float64')

In [13]:
array_4 = np.arange(1,10,2) 
print(type(array_4),array_4)
array_4

<class 'numpy.ndarray'> [1 3 5 7 9]


array([1, 3, 5, 7, 9])

In [46]:
np.zeros([5,1]) # (5,1) 不行
print(type(np.zeros([5])),np.zeros(5),np.zeros([5,1]),np.zeros([5,1]).dtype)

<class 'numpy.ndarray'> [0. 0. 0. 0. 0.] [[0.]
 [0.]
 [0.]
 [0.]
 [0.]] float64


In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 #### 访问

In [25]:
a = np.arange(1,10)

In [26]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a[3]  # 索引

4

In [28]:
a[2:4] #  切片  前包后不包

array([3, 4])

In [29]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
b[1][0]

4

In [31]:
b[1,0]  # 

4

In [39]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
c.ndim  # 维数 3*3 

2

In [41]:
c[:2,1:]  # 切片， 前包后不包

array([[2, 3],
       [5, 6]])