### 快速创建数组

In [1]:
import numpy as np 

In [2]:
np.random.randn(10)

array([-0.4437916 , -1.48884523, -0.16395987,  1.03375531,  0.99898   ,
        1.80309889, -0.35036963,  0.7549138 ,  0.84783552, -0.64701167])

In [8]:
np.random.randint(0)

ValueError: low >= high

In [9]:
np.random.randint(10)

8

In [13]:
np.random.randint(10,size=[2,10]).reshape([4,5])

array([[9, 8, 2, 2, 0],
       [7, 5, 0, 5, 1],
       [4, 5, 5, 6, 5],
       [0, 2, 5, 8, 4]])

In [14]:
a = np.random.randint(10,size = 20).reshape(4,5)
b = np.random.randint(10,size = 20).reshape([4,5])

In [15]:
a

array([[3, 9, 6, 7, 7],
       [6, 2, 8, 5, 5],
       [9, 5, 8, 7, 5],
       [4, 7, 7, 7, 7]])

In [16]:
b

array([[2, 1, 4, 2, 3],
       [8, 6, 3, 7, 5],
       [9, 2, 7, 9, 5],
       [4, 4, 5, 2, 1]])

In [17]:
a-b

array([[ 1,  8,  2,  5,  4],
       [-2, -4,  5, -2,  0],
       [ 0,  3,  1, -2,  0],
       [ 0,  3,  2,  5,  6]])

In [18]:
a+b

array([[ 5, 10, 10,  9, 10],
       [14,  8, 11, 12, 10],
       [18,  7, 15, 16, 10],
       [ 8, 11, 12,  9,  8]])

In [19]:
a*b  # 对应元素相乘

array([[ 6,  9, 24, 14, 21],
       [48, 12, 24, 35, 25],
       [81, 10, 56, 63, 25],
       [16, 28, 35, 14,  7]])

In [20]:
a/b  #  当b中有0时会警告， inf无穷大

array([[1.5       , 9.        , 1.5       , 3.5       , 2.33333333],
       [0.75      , 0.33333333, 2.66666667, 0.71428571, 1.        ],
       [1.        , 2.5       , 1.14285714, 0.77777778, 1.        ],
       [1.        , 1.75      , 1.4       , 3.5       , 7.        ]])

In [21]:
mat_1 = np.mat([[1,2,3],[4,5,6]])
mat_1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [24]:
print(type(mat_1),mat_1)

<class 'numpy.matrixlib.defmatrix.matrix'> [[1 2 3]
 [4 5 6]]


In [22]:
np.mat(a)

matrix([[3, 9, 6, 7, 7],
        [6, 2, 8, 5, 5],
        [9, 5, 8, 7, 5],
        [4, 7, 7, 7, 7]])

#### 矩阵的运算

In [25]:
A= np.mat(a)
B = np.mat(b)

In [27]:
A

matrix([[3, 9, 6, 7, 7],
        [6, 2, 8, 5, 5],
        [9, 5, 8, 7, 5],
        [4, 7, 7, 7, 7]])

In [28]:
B

matrix([[2, 1, 4, 2, 3],
        [8, 6, 3, 7, 5],
        [9, 2, 7, 9, 5],
        [4, 4, 5, 2, 1]])

In [29]:
A+B

matrix([[ 5, 10, 10,  9, 10],
        [14,  8, 11, 12, 10],
        [18,  7, 15, 16, 10],
        [ 8, 11, 12,  9,  8]])

In [30]:
A-B


matrix([[ 1,  8,  2,  5,  4],
        [-2, -4,  5, -2,  0],
        [ 0,  3,  1, -2,  0],
        [ 0,  3,  2,  5,  6]])

In [31]:
A*B

ValueError: shapes (4,5) and (4,5) not aligned: 5 (dim 1) != 4 (dim 0)

In [32]:
A = np.mat(np.random.randint(10,size = 20).reshape(4,5))
B = np.mat(np.random.randint(10,size = 20).reshape(5,4))

In [33]:
A*B

matrix([[113, 125,  72,  22],
        [123, 168, 138,  61],
        [137, 219,  81,  80],
        [154, 246, 116,  90]])

#### Array的常用函数

In [35]:
a = np.random.randint(10,size = 20).reshape(4,5)
a

array([[5, 5, 8, 6, 9],
       [8, 3, 6, 8, 7],
       [1, 6, 1, 8, 5],
       [1, 9, 8, 5, 6]])

In [36]:
np.unique(a)

array([1, 3, 5, 6, 7, 8, 9])

In [37]:
sum(a)

array([15, 23, 23, 27, 27])

In [38]:
sum(a[0])

33

In [39]:
sum(a[:,0])

15

In [40]:
a.max()

9

In [41]:
max(a[0])

9

In [42]:
max(a[:,0])

8