In [1]:
import numpy as np
import pandas as pd 
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape([3,3])
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
arr2 = np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr2]) # 拼接矩阵 6*3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr2],axis=1) # 3*6

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

# series

In [9]:
s1 = Series([1,2,3],index=["x","y","z"])
s2 = Series([4,5],index = ["A","B"])

In [10]:
s1

x    1
y    2
z    3
dtype: int64

In [11]:
s2

A    4
B    5
dtype: int64

In [16]:
pd1 = pd.concat([s1,s2])
print(type(pd1))
pd1

<class 'pandas.core.series.Series'>


x    1
y    2
z    3
A    4
B    5
dtype: int64

In [18]:
pd.concat([s1,s2],axis = 1)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


0    1
A  NaN  4.0
B  NaN  5.0
x  1.0  NaN
y  2.0  NaN
z  3.0  NaN

# DataFrame

In [21]:
df1 = DataFrame(np.random.randn(3,3),columns=["X",'Y','Z'])
df1

X         Y         Z
0  2.272396 -1.869448 -1.500646
1 -0.192573 -0.224680  0.316689
2  0.746760  0.348303 -0.168941

In [22]:
df2 = DataFrame(np.random.randn(3,3),columns=['X','Y','A'])
df2

X         Y         A
0 -1.070525  0.591445 -0.702120
1  1.751966  0.289966  0.526991
2  1.952398 -0.819621 -0.155868

In [24]:
pd.concat([df1,df2])

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.


A         X         Y         Z
0       NaN  2.272396 -1.869448 -1.500646
1       NaN -0.192573 -0.224680  0.316689
2       NaN  0.746760  0.348303 -0.168941
0 -0.702120 -1.070525  0.591445       NaN
1  0.526991  1.751966  0.289966       NaN
2 -0.155868  1.952398 -0.819621       NaN

# combine

In [6]:
s1 = Series([2,np.nan,4],index=["A","B","C",])
s1

A    2.0
B    NaN
C    4.0
dtype: float64

In [7]:
s2 = Series([1,2,3,4],index=["A","B","C","D"])
s2

A    1
B    2
C    3
D    4
dtype: int64

In [8]:
s1.combine_first(s2)  # 用s2 去填充s1

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [29]:
df1 = DataFrame({
    "X":[1,np.nan,3,np.nan],
    "Y":[5,np.nan,7,np.nan],
    "Z":[9,np.nan,11,np.nan]
    
})
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [33]:
df2 = DataFrame({
    "Z":[3,10,np.nan,12],
    "A":[1,2,3,4]
})
df2

Z  A
0   3.0  1
1  10.0  2
2   NaN  3
3  12.0  4

In [34]:
df1.combine_first(df2)  # 用df2 去填充df1 ，两个都有以df1为准

A    X    Y     Z
0  1.0  1.0  5.0   9.0
1  2.0  NaN  NaN  10.0
2  3.0  3.0  7.0  11.0
3  4.0  NaN  NaN  12.0